# The URL the site will be built for
base_url = "https://100phlecs.github.io"
description = "rantbox"
generate_feed = true
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
{name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
# Enable syntax highlighting
highlight_code = true
# Instead of adding inline styles export styles as CSS files.
highlight_theme = "css"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "phil"
favicon = "favicon.ico"
list_pages = false
twitter_card = true


[[extra.header_nav]]
en = { name = "/home/", url = "/" }


[[extra.header_nav]]
en = { name = "/journal/", url = "/journal" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }

