#+title: Sludge and Oil
#+date: 11-30-21 (edit 12-01-21)

Our subconsious has considerable influence on reality.  It is touted
that [[https://hbswk.hbs.edu/item/the-subconscious-mind-of-the-consumer-and-how-to-reach-it][90 to 95 percent of some behavior]] is controlled by our
subconscious. Who knows what else! Most like to twist this fact into
some deterministic futilism and sure, you certainly could. But there's
still that 10 percent, and that 10 percent is what, I figure, hits the
subconscious button to "go do that" or "this" and so on. That is, you
still choose what to do. Which means you still choose who you are.

How do you choose who you are? You choose by what you pay attention
to! Consider all of your memories, the things you know, and how you
think you just "know" it by thinking it -- consider all of that and
then throw in your subconscious into the mix. How is your subconsious
involved with your information? It probably absorbs everything. Do you
want your subconsious to mingle with magazine headlines or with math
problems?

#+begin_quote
You choose by what you pay attention to!
#+end_quote


When you think about how almost every experience or sentence read
touches your subsconsious, you can start to picture it as either
*sludge* or *oil*. It _accumulates_. *Sludge* can harden, mold, calcify,
degrade and ruin. *Oil* keeps one nimble and swishes around all ideas,
makes connections. Keeps gears moving. With accumulation in mind, one
can see the weight behind the adage "can't teach an old dog new
tricks". Everything /sinks/ into you and builds up until there's no way
to dig that crud out.

#+attr_html: :style width: 50% 
file:../assets/sludge.jpg


So one ought to start managing their sludge and oil. For example, one
may "quickly" on Facebook, but that site visit will imprint itself
into... your everything, I suppose. Who you are. You become an
Facebook User and everything that word means (the general personality
found in such places). Your behavior, actions, who you are... all
comes from the subconsious. With _accumulation_ in mind, it means that
you can't hide who you are. We are what we repeatedly do, as the
Greeks knew.
